name: Build, Test, and Deploy

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

permissions:
  contents: write

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Cache SBT dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.ivy2/cache
            ~/.sbt
          key: ${{ runner.os }}-sbt-${{ hashFiles('**/build.sbt') }}

      - name: Build and Test
        run: sbt clean compile test fastLinkJS

      - name: Create index.html and copy JS files
        run: |
          mkdir -p target/scala-3.4.2/classes
          echo '<html>
          <head>
          <meta charset="UTF-8">
          <title>Tyrian Counter Example</title>
          </head>
          <body>
          <div id="myapp"></div>
          <script type="module" src="./main.js"></script>
          </body>
          </html>' > target/scala-3.4.2/classes/index.html
          cp target/scala-3.4.2/pps-tyranexample-fastopt/main.js target/scala-3.4.2/classes/
          cp tyrianapp.js target/scala-3.4.2/classes/

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/master'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./target/scala-3.4.2/classes